# Generated by Django 4.2.11 on 2024-04-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_general', '0004_remove_address_account_delete_account_delete_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slides/')),
                ('caption', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
