# Generated by Django 4.2.9 on 2024-05-16 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
