# Generated by Django 4.2.9 on 2024-05-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adminorder',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('PENDING', 'รอดำเนินการ'), ('PROCESSING', 'กำลังดำเนินการ'), ('SHIPPED', 'จัดส่งแล้ว'), ('DELIVERED', 'จัดส่งสำเร็จ'), ('CANCELLED', 'ยกเลิก')], default='PENDING', max_length=20),
        ),
    ]
