# Generated by Django 4.2.9 on 2024-05-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_adminorder_tracking_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('pickup', 'รับที่ร้าน'), ('delivery', 'จัดส่ง')], default='pickup', max_length=20),
        ),
    ]
