# Generated by Django 4.2.9 on 2024-05-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_order_delivery_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('pickup', 'รับที่ร้าน'), ('delivery', 'จัดส่ง')], max_length=20),
        ),
    ]
