# Generated by Django 4.2.9 on 2024-05-31 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_order_delivery_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='delivery_method',
            field=models.CharField(choices=[('pickup', 'รับที่ร้าน'), ('delivery', 'จัดส่ง')], default='pickup', max_length=20),
        ),
    ]
