# Generated by Django 4.2.9 on 2024-05-07 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_adminorder_order_adminorder_shipping_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentupload',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='cart.order'),
        ),
    ]
