# Generated by Django 4.2.9 on 2024-05-13 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_paymentupload_order'),
    ]

    operations = [
    ]
