# Generated by Django 4.2.9 on 2024-05-16 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_auto_20240513_1635'),
    ]

    operations = [
    migrations.AlterField(
        model_name='adminorder',
        name='order',
        field=models.ForeignKey(null=True, on_delete=models.CASCADE, to='cart.order'),
    ),
    migrations.AlterField(
        model_name='paymentupload',
        name='order',
        field=models.ForeignKey(null=True, on_delete=models.CASCADE, to='cart.order'),
    ),
]

