# Generated by Django 4.2.9 on 2024-06-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_remove_order_shipping_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('PENDING', 'รอดำเนินการ'), ('PROCESSING', 'กำลังดำเนินการ'), ('PREPARED', 'เตรียมของเสร็จแล้ว'), ('SHIPPED', 'จัดส่งแล้ว'), ('DELIVERED', 'จัดส่งสำเร็จ'), ('RECEIVED', 'รับสินค้าแล้ว'), ('CANCELLED', 'ยกเลิก')], default='PENDING', max_length=20),
        ),
    ]
