# Generated by Django 4.2.9 on 2024-05-16 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_alter_paymentupload_order'),
    ]

    operations = [
    ]
