# Generated by Django 4.2.9 on 2024-05-24 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_auto_20240516_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminorder',
            name='order',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='cart.order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentupload',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='cart.order'),
        ),
    ]
