# Generated by Django 4.2.9 on 2024-06-08 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingCost',
        ),
    ]
